//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int borrowId { get; set; }
        public int studentId { get; set; }
        public int bookId { get; set; }
        public System.DateTime takenDate { get; set; }
        public System.DateTime broughtDate { get; set; }
        public int returned { get; set; }

        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
